void fonction(){ 
 digitalWrite(6, HIGH); 
 delay(40);  
 digitalWrite(7, HIGH); 
 delay(40); 
 digitalWrite(8, HIGH); 
 delay(40); 
 digitalWrite(9, HIGH); 
 delay(40); 
 digitalWrite(10, HIGH); 
 delay(40); 
 digitalWrite(11, HIGH);  
 delay(40); 
 delay(40); 
 digitalWrite(2,HIGH); 
 delay(40); 
 digitalWrite(3, HIGH); 
 delay(40); 
 digitalWrite(4, HIGH); 
 delay(40); 
 digitalWrite(5,HIGH); 
 delay(40); 
 delay(1000); 
 digitalWrite(6, LOW); 
  delay(40); 
 digitalWrite(7,LOW); 
  delay(40); 
 digitalWrite(8, LOW); 
 delay(40); 
 digitalWrite(9, LOW); 
 delay(40); 
 digitalWrite(10, LOW); 
 delay(40);
 digitalWrite(11, LOW); 
 delay(40); 
 delay(40); 
 digitalWrite(2,LOW); 
 delay(40); 
 digitalWrite(3, LOW); 
 delay(40); 
 digitalWrite(4, LOW); 
  delay(40); 
 digitalWrite(5,LOW); 
  delay(40); 
 }